### ISSUE TITLE
issues when using happymapper 0.3.0

### ISSUE THREAD

**Issue by jimiray** [Fosome/garb#11]
Just noticed that there are issues when upgrading happy mapper to 0.3.0 looking into them further.

**Comment by tpitale** [comment]
Thanks, I'll look into it asap.

**Comment by vince** [comment]
seeing this as well: undefined method `from_ga' for nil:NilClass

**Comment by tpitale** [comment]
Version 0.2.7 of garb fixes this and requires 0.3.0 of happymapper.

I'm having difficulty getting back ownership of garb on gemcutter so that I can push this up there. Until then you'll have to clone and build the gem.

**Comment by jimiray** [comment]
thanks.

**Comment by tpitale** [comment]
0.3.1 of garb should be up on gemcutter now, fyi.
